sonar.projectKey=AparnaMounikau763_SonarQube-integration-task
sonar.organization=aparnamounikau763

sonar.sources=app
sonar.tests=tests
sonar.exclusions=tests/**,**/__pycache__/**

sonar.python.version=3.10
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml