sonar.projectKey=my-python-app
sonar.organization=my-org

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.10
sonar.sourceEncoding=UTF-8

# Coverage
sonar.python.coverage.reportPaths=coverage.xml